version: '3.0'

services:
  grafana:
    user: root
    container_name: 'koudai-grafanareact-panel'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.5.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/koudai-grafanareact-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/koudai-grafanareact-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.koudai-grafanareact-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: koudai-grafanareact-panel
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource
